---
title: Cognitive complexity
---

```{r cog-include-setup, include=FALSE}
source(knitr::purl('setup.Rmd', output=tempfile()))
```

This section covers the analysis relating to the _cognitive complexity_ metric.

## Data preparation

```{r cog-data-preparation, message=FALSE}
model_seed <- 20230403 # 2023 April 3

create_cognitive_complexity_data <- function(data) {
  list(
    cognitive_complexity_kloc_std=scale(data$cognitive_complexity_kloc),
                 contributors_std=scale(data$contributors),
                        stars_std=scale(data$stars),
                        files_std=scale(data$files),
                         size_std=scale(data$loc),
                          age_std=scale(get_age(data$created_at))
  )
}

data <- create_cognitive_complexity_data(df)
data$category <- factor(df$category)
```

## Candidate models {.tabset}

### COG1

```{r cog-model-1, message=FALSE}
fit_model_cog1 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog1 <- fit_model_cog1("cog1", data)
```

### COG2

```{r cog-model-2, message=FALSE}
fit_model_cog2 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog2 <- fit_model_cog2("cog2", data)
```

### COG3

```{r cog-model-3, message=FALSE}
fit_model_cog3 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog3 <- fit_model_cog3("cog3", data)
```

### COG4

```{r cog-model-4, message=FALSE}
fit_model_cog4 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog4 <- fit_model_cog4("cog4", data)
```

### COG5

```{r cog-model-5, message=FALSE}
fit_model_cog5 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + files_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="files_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog5 <- fit_model_cog5("cog5", data)
```

### COG6

```{r cog-model-6, message=FALSE}
fit_model_cog6 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog6 <- fit_model_cog6("cog6", data)
```

### COG7

```{r cog-model-7, message=FALSE}
fit_model_cog7 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + size_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog7 <- fit_model_cog7("cog7", data)
```

### COG8

```{r cog-model-8, message=FALSE}
fit_model_cog8 <- function(name, data) {
  fit_model(name,
            "cognitive_complexity_kloc_std ~ 0 + category + size_std + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

cog8 <- fit_model_cog8("cog8", data)
```

## Model comparison

```{r cog-model-comparison, message=FALSE, warning=FALSE}
cog1 <- add_criterion(cog1, criterion="loo", moment_match=TRUE)
cog2 <- add_criterion(cog2, criterion="loo", moment_match=TRUE)
cog3 <- add_criterion(cog3, criterion="loo", moment_match=TRUE)
cog4 <- add_criterion(cog4, criterion="loo", moment_match=TRUE)
cog5 <- add_criterion(cog5, criterion="loo", moment_match=TRUE)
cog6 <- add_criterion(cog6, criterion="loo", moment_match=TRUE)
cog7 <- add_criterion(cog7, criterion="loo", moment_match=TRUE)
cog8 <- add_criterion(cog8, criterion="loo", moment_match=TRUE)

print(loo_compare(cog1, cog2, cog3, cog4, cog5, cog6, cog7, cog8, criterion="loo"),
      simplify=FALSE)
```

## Diagnostics {.tabset}

### Prior predictive check

```{r cog-ppc, message=FALSE}
plot_priors(cog5, "Cognitive complexity per KLOC (std)")
```

### MCMC chain trace plots

```{r cog-caterpillars, message=FALSE}
plot_caterpillar(cog5, "b_category1", "N")
plot_caterpillar(cog5, "b_category2", "A")
plot_caterpillar(cog5, "b_category3", "AE")
plot_caterpillar(cog5, "b_category5", "AEP")
plot_caterpillar(cog5, "b_category7", "AEP+")
```

## Estimates {.tabset}

### Standardized

```{r cog-standardized-estimates, message=FALSE}
summary(cog5)
```

### Natural scale

```{r cog-natural-scale-estimates, message=FALSE}
print(create_natural_scale_summary_df(cog5, df$cognitive_complexity_kloc))
```

## Plots {.tabset}

### Major category intervals

```{r cog-major-category-intervals, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(cog5) +
  labs(title="COG5", x="Cognitive complexity per KLOC (std)")
```

### Binary warning usage

```{r cog-warnings-vs-no-warnings, fig.height=2, message=FALSE}
data_binary_factor <- create_cognitive_complexity_data(df)
data_binary_factor$category <- factor(uses_warnings(df$category))

cog5_binary_factor <- fit_model_cog5("cog5_factor_uses_warnings",
                                     data_binary_factor)

plot_intervals_of_categories(cog5_binary_factor) +
  labs(title="COG5", x="Cognitive complexity per KLOC (std)") +
  scale_y_discrete(labels=c(
                     "b_category1"="No warnings",
                     "b_category2"="Any warnings"
                   ))
```
