---
title: Duplicated lines
---

```{r dl-include-setup, include=FALSE}
source(knitr::purl('setup.Rmd', output=tempfile()))
```

This section covers the analysis relating to the _duplicated lines_ metric.

## Data preparation

```{r dl-data-preparation}
model_seed <- 20230403 # 2023 April 3

create_duplicated_lines_data <- function(data) {
  list(
    duplicated_lines_kloc_std=scale(data$duplicated_lines_kloc),
             contributors_std=scale(data$contributors),
                    stars_std=scale(data$stars),
                    files_std=scale(data$files),
                     size_std=scale(data$loc),
                      age_std=scale(get_age(data$created_at))
  )
}

data <- create_duplicated_lines_data(df)
data$category <- factor(df$category)
```

## Candidate models {.tabset}

### D1

```{r dl-model-1, message=FALSE}
fit_model_d1 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d1 <- fit_model_d1("d1", data)
```

### D2

```{r d-model-2, message=FALSE}
fit_model_d2 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d2 <- fit_model_d2("d2", data)
```

### D3

```{r dl-model-3, message=FALSE}
fit_model_d3 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d3 <- fit_model_d3("d3", data)
```

### D4

```{r dl-model-4, message=FALSE}
fit_model_d4 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d4 <- fit_model_d4("d4", data)
```

### D5

```{r dl-model-5, message=FALSE}
fit_model_d5 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d5 <- fit_model_d5("d5", data)
```

### D6

```{r dl-model-6, message=FALSE}
fit_model_d6 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + files_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="files_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d6 <- fit_model_d6("d6", data)
```

### D7

```{r dl-model-7, message=FALSE}
fit_model_d7 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + contributors_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d7 <- fit_model_d7("d7", data)
```

### D8

```{r dl-model-8, message=FALSE}
fit_model_d8 <- function(name, data) {
  fit_model(name,
            "duplicated_lines_kloc_std ~ 0 + category + contributors_std + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

d8 <- fit_model_d8("d8", data)
```

## Model comparison

```{r dl-model-comparison, message=FALSE}
d1 <- add_criterion(d1, criterion="loo")
d2 <- add_criterion(d2, criterion="loo")
d3 <- add_criterion(d3, criterion="loo")
d4 <- add_criterion(d4, criterion="loo")
d5 <- add_criterion(d5, criterion="loo")
d6 <- add_criterion(d6, criterion="loo")
d7 <- add_criterion(d7, criterion="loo")
d8 <- add_criterion(d8, criterion="loo")

print(loo_compare(d1, d2, d3, d4, d5, d6, d7, d8, criterion="loo"),
      simplify=FALSE)
```

## Diagnostics {.tabset}

### Prior predictive check

```{r dl-ppc, message=FALSE}
plot_priors(d6, "Duplicated lines per KLOC (std)")
```

### MCMC chain trace plots

```{r dl-caterpillars, message=FALSE}
plot_caterpillar(d6, "b_category1", "N")
plot_caterpillar(d6, "b_category2", "A")
plot_caterpillar(d6, "b_category3", "AE")
plot_caterpillar(d6, "b_category5", "AEP")
plot_caterpillar(d6, "b_category7", "AEP+")
```

## Estimates {.tabset}

### Standardized

```{r dl-standardized-estimates, message=FALSE}
summary(d6)
```

### Natural scale

```{r dl-natural-scale-estimates, message=FALSE}
print(create_natural_scale_summary_df(d6, df$duplicated_lines_kloc))
```

## Plots {.tabset}

### Major category intervals

```{r dl-major-category-intervals, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(d6) +
  labs(title="D6", x="Duplicated lines per KLOC (std)")
```

### Binary warning usage

```{r dl-binary-warning-usage, fig.height=2, message=FALSE}
data_binary_factor <- create_duplicated_lines_data(df)
data_binary_factor$category <- factor(uses_warnings(df$category))

d6_binary_factor <- fit_model_d6("d6_factor_uses_warnings",
                                 data_binary_factor)

plot_intervals_of_categories(d6_binary_factor) +
  labs(title="D6", x="Duplicated lines per KLOC (std)") +
  scale_y_discrete(labels=c(
                     "b_category1"="No warnings",
                     "b_category2"="Any warnings"
                   ))
```
