---
title: Minor violations
---

```{r miv-include-setup, include=FALSE}
source(knitr::purl('setup.Rmd', output = tempfile()))
```

This section covers the analysis relating to the _minor violations_ metric.

## Data preparation

```{r miv-prepare-data}
model_seed <- 20230328  # 2023 March 28

create_minor_violations_data <- function(data) {
  list(
    minor_violations_kloc_std=scale(data$minor_violations_kloc),
             contributors_std=scale(data$contributors),
                    stars_std=scale(data$stars),
                    files_std=scale(data$files),
                     size_std=scale(data$loc),
                      age_std=scale(get_age(data$created_at))
  )
}

data <- create_minor_violations_data(df)
data$category <- factor(df$category)
```

## Candidate models {.tabset}

### MIV1

```{r miv-model-1, message=FALSE}
fit_model_miv1 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv1 <- fit_model_miv1("miv1", data)
```

### MIV2

```{r miv-model-2, message=FALSE}
fit_model_miv2 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv2 <- fit_model_miv2("miv2", data)
```

### MIV3

```{r miv-model-3, message=FALSE}
fit_model_miv3 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv3 <- fit_model_miv3("miv3", data)
```

### MIV4

```{r miv-model-4, message=FALSE}
fit_model_miv4 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + files_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="files_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv4 <- fit_model_miv4("miv4", data)
```

### MIV5

```{r miv-model-5, message=FALSE}
fit_model_miv5 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv5 <- fit_model_miv5("miv5", data)
```

### MIV6

```{r miv-model-6, message=FALSE}
fit_model_miv6 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv6 <- fit_model_miv6("miv6", data)
```

### MIV7

```{r miv-model-7, message=FALSE}
fit_model_miv7 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + contributors_std + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv7 <- fit_model_miv7("miv7", data)
```

### MIV8

```{r miv-model-8, message=FALSE}
fit_model_miv8 <- function(name, data) {
  fit_model(name,
            "minor_violations_kloc_std ~ 0 + category + contributors_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

miv8 <- fit_model_miv8("miv8", data)
```

## Model comparison

```{r miv-model-comparisons}
miv1 <- add_criterion(miv1, criterion="loo", moment_match=TRUE)
miv2 <- add_criterion(miv2, criterion="loo", moment_match=TRUE)
miv3 <- add_criterion(miv3, criterion="loo", moment_match=TRUE)
miv4 <- add_criterion(miv4, criterion="loo", moment_match=TRUE)
miv5 <- add_criterion(miv5, criterion="loo", moment_match=TRUE)
miv6 <- add_criterion(miv6, criterion="loo", moment_match=TRUE)
miv7 <- add_criterion(miv7, criterion="loo", moment_match=TRUE)
miv8 <- add_criterion(miv8, criterion="loo", moment_match=TRUE)

print(loo_compare(miv1, miv2, miv3, miv4, miv5, miv6, miv7, miv8, criterion="loo"),
      simplify=FALSE)
```

## Diagnostics {.tabset}

### Prior predictive check

```{r miv-ppc}
plot_priors(miv1, "Minor violations per KLOC (std)")
```

### MCMC chain trace plots

```{r miv-caterpillars, message=FALSE}
plot_caterpillar(miv1, "b_category1", "N")
plot_caterpillar(miv1, "b_category2", "A")
plot_caterpillar(miv1, "b_category3", "AE")
plot_caterpillar(miv1, "b_category5", "AEP")
plot_caterpillar(miv1, "b_category7", "AEP+")
```

## Estimates {.tabset}

### Standardized

```{r miv-standardized-estimates, message=FALSE}
summary(miv1)
```

### Natural scale

```{r miv-natural-scale-estimates, message=FALSE}
print(create_natural_scale_summary_df(miv1, df$minor_violations_kloc))
```

## Plots {.tabset}

### Major category intervals

```{r miv-major-category-intervals, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(miv1) +
  labs(title="MIV1", x="Minor violations per KLOC (std)")
```

### Binary warning factor

```{r miv-binary-warning-factor, fig.height=2, message=FALSE}
data_binary_factor <- create_minor_violations_data(df)
data_binary_factor$category <- factor(uses_warnings(df$category))

miv1_binary_factor <- fit_model_miv1("miv1_factor_uses_warnings",
                                     data_binary_factor)

plot_intervals_of_categories(miv1_binary_factor) +
  labs(title="MIV1", x="Minor violations per KLOC (std)") +
  scale_y_discrete(labels=c(
                     "b_category1"="No warnings",
                     "b_category2"="Any warnings"
                   ))
```
