---
title: Security hotspots
---

```{r s-include-setup, include=FALSE}
source(knitr::purl('setup.Rmd', output=tempfile()))
```

This section covers the analysis relating to the _security hotspots_ metric.

## Data preparation

```{r s-prepare-data}
model_seed <- 20230330  # 2023 March 30

create_security_hotspots_data <- function(data) {
  list(
    security_hotspots_kloc_std=scale(data$security_hotspots_kloc),
              contributors_std=scale(data$contributors),
                     stars_std=scale(data$stars),
                     files_std=scale(data$files),
                      size_std=scale(data$loc),
                       age_std=scale(get_age(data$created_at))
  )
}

data <- create_security_hotspots_data(df)
data$category <- factor(df$category)
```

## Candidate models {.tabset}

### S1

```{r s-model-1, message=FALSE}
fit_model_s1 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s1 <- fit_model_s1("s1", data)
```

### S2

```{r s-model-2, message=FALSE}
fit_model_s2 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s2 <- fit_model_s2("s2", data)
```

### S3

```{r s-model-3, message=FALSE}
fit_model_s3 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s3 <- fit_model_s3("s3", data)
```

### S4

```{r s-model-4, message=FALSE}
fit_model_s4 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s4 <- fit_model_s4("s4", data)
```

### S5

```{r s-model-5, message=FALSE}
fit_model_s5 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + files_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="files_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s5 <- fit_model_s5("s5", data)
```

### S6

```{r s-model-6, message=FALSE}
fit_model_s6 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s6 <- fit_model_s6("s6", data)
```

### S7

```{r s-model-7, message=FALSE}
fit_model_s7 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + contributors_std + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s7 <- fit_model_s7("s7", data)
```

### S8

```{r s-model-8, message=FALSE}
fit_model_s8 <- function(name, data) {
  fit_model(name,
            "security_hotspots_kloc_std ~ 0 + category + contributors_std + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

s8 <- fit_model_s8("s8", data)
```

## Model comparison

```{r s-model-comparisons, message=FALSE}
s1 <- add_criterion(s1, criterion="loo", moment_match=TRUE)
s2 <- add_criterion(s2, criterion="loo", moment_match=TRUE)
s3 <- add_criterion(s3, criterion="loo", moment_match=TRUE)
s4 <- add_criterion(s4, criterion="loo", moment_match=TRUE)
s5 <- add_criterion(s5, criterion="loo", moment_match=TRUE)
s6 <- add_criterion(s6, criterion="loo", moment_match=TRUE)
s7 <- add_criterion(s7, criterion="loo", moment_match=TRUE)
s8 <- add_criterion(s8, criterion="loo", moment_match=TRUE)

print(loo_compare(s1, s2, s3, s4, s5, s6, s7, s8, criterion="loo"),
      simplify=FALSE)
```

## Diagnostics {.tabset}

### Prior predictive check

```{r s-ppc}
plot_priors(s2, "Security hotspots per KLOC (std)")
```

### MCMC chain trace plots

```{r s-caterpillars, message=FALSE}
plot_caterpillar(s2, "b_category1", "N")
plot_caterpillar(s2, "b_category2", "A")
plot_caterpillar(s2, "b_category3", "AE")
plot_caterpillar(s2, "b_category5", "AEP")
plot_caterpillar(s2, "b_category7", "AEP+")
```

## Estimates {.tabset}

### Standardized

```{r s-standardized-estimates, message=FALSE}
summary(s2)
```

### Natural scale

```{r s-natural-scale-estimates, message=FALSE}
print(create_natural_scale_summary_df(s2, df$security_hotspots_kloc))
```

## Plots {.tabset}

### Major category intervals

```{r s-major-category-intervals, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(s2) +
  labs(title="S2", x="Security hotspots per KLOC (std)")
```

### Binary warning usage

```{r s-binary-warning-usage, fig.height=2, message=FALSE}
data_binary_factor <- create_security_hotspots_data(df)
data_binary_factor$category <- factor(uses_warnings(df$category))

s2_binary_factor <- fit_model_s2("s2_factor_uses_warnings", data_binary_factor)

plot_intervals_of_categories(s2_binary_factor) +
  labs(title="S2", x="Security hotspots per KLOC (std)") +
  scale_y_discrete(labels=c(
                     "b_category1"="No warnings",
                     "b_category2"="Any warnings"
                   ))
```
