---
title: Vulnerabilities
---

```{r v-include-setup, include=FALSE}
source(knitr::purl('setup.Rmd', output=tempfile()))
```

This section covers the analysis relating to the _vulnerabilities_ metric.

## Data preparation

```{r v-data-preparation, message=FALSE}
model_seed <- 20230330  # 2023 March 30

create_vulnerabilities_data <- function(data) {
  list(
    vulnerabilities_kloc_std=scale(data$vulnerabilities_kloc),
            contributors_std=scale(data$contributors),
                   stars_std=scale(data$stars),
                   files_std=scale(data$files),
                    size_std=scale(data$loc),
                     age_std=scale(get_age(data$created_at))
  )
}

data <- create_vulnerabilities_data(df)
data$category <- factor(df$category)
```

## Candidate models {.tabset}

### V1

```{r v-model-1, message=FALSE}
fit_model_v1 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v1 <- fit_model_v1("v1", data)
```

### V2

```{r v-model-2, message=FALSE}
fit_model_v2 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v2 <- fit_model_v2("v2", data)
```

### V3

```{r v-model-3, message=FALSE}
fit_model_v3 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v3 <- fit_model_v3("v3", data)
```

### V4

```{r v-model-4, message=FALSE}
fit_model_v4 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v4 <- fit_model_v4("v4", data)
```

### V5

```{r v-model-5, message=FALSE}
fit_model_v5 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v5 <- fit_model_v5("v5", data)
```

### V6

```{r v-model-6, message=FALSE}
fit_model_v6 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + files_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="files_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v6 <- fit_model_v6("v6", data)
```

### V7

```{r v-model-7, message=FALSE}
fit_model_v7 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + contributors_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v7 <- fit_model_v7("v7", data)
```

### V8

```{r v-model-8, message=FALSE}
fit_model_v8 <- function(name, data) {
  fit_model(name,
            "vulnerabilities_kloc_std ~ 0 + category + contributors_std + size_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="size_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

v8 <- fit_model_v8("v8", data)
```

## Model comparison

```{r v-model-comparison, message=FALSE}
v1 <- add_criterion(v1, criterion="loo", moment_match=TRUE)
v2 <- add_criterion(v2, criterion="loo", moment_match=TRUE)
v3 <- add_criterion(v3, criterion="loo", moment_match=TRUE)
v4 <- add_criterion(v4, criterion="loo", moment_match=TRUE)
v5 <- add_criterion(v5, criterion="loo", moment_match=TRUE)
v6 <- add_criterion(v6, criterion="loo", moment_match=TRUE)
v7 <- add_criterion(v7, criterion="loo", moment_match=TRUE)
v8 <- add_criterion(v8, criterion="loo", moment_match=TRUE)

print(loo_compare(v1, v2, v3, v4, v5, v6, v7, v8, criterion="loo"),
      simplify=FALSE)
```

## Diagnostics {.tabset}

### Prior predictive check

```{r v-ppc, message=FALSE}
plot_priors(v1, "Vulnerabilities per KLOC (std)")
```

### MCMC chain trace plots

```{r v-caterpillars, message=FALSE}
plot_caterpillar(v1, "b_category1", "N")
plot_caterpillar(v1, "b_category2", "A")
plot_caterpillar(v1, "b_category3", "AE")
plot_caterpillar(v1, "b_category5", "AEP")
plot_caterpillar(v1, "b_category7", "AEP+")
```

## Estimates {.tabset}

### Standardized

```{r v-standardized-estimates, message=FALSE}
summary(v1)
```

### Natural scale

```{r v-natural-scale-estimates, message=FALSE}
print(create_natural_scale_summary_df(v1, df$vulnerabilities_kloc, precision=6))
```

## Plots {.tabset}

### Major category intervals

```{r v-major-category-intervals, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(v1) +
  labs(title="V1", x="Vulnerabilities per KLOC (std)")
```

### Binary warning usage

```{r v-binary-warning-usage, fig.height=2, message=FALSE}
data_binary_factor <- create_vulnerabilities_data(df)
data_binary_factor$category <- factor(uses_warnings(df$category))

v1_binary_factor <- fit_model_v1("v1_factor_uses_warnings", data_binary_factor)

plot_intervals_of_categories(v1_binary_factor) +
  labs(title="V1", x="Vulnerabilities per KLOC (std)") +
  scale_y_discrete(labels=c(
                     "b_category1"="No warnings",
                     "b_category2"="Any warnings"
                   ))
```
