---
author: Albin Johansson & Carl Holmberg
date: 2023
---

```{r b-include-setup, include=FALSE}
source(knitr::purl('pages/setup.Rmd', output = tempfile()))
```

# Bugs

This section covers the analysis relating to the "bugs" metric.

## Prepare data

```{r b-prepare-data}
# The model seed is the date that the analysis was conducted
model_seed <- 20230303

# Returns a list of standardized data necessary for the analysis.
create_bugs_data <- function(data) {
  list(
       bugs_kloc_std=scale(data$bugs_kloc),
    contributors_std=scale(data$contributors),
           stars_std=scale(data$stars),
            size_std=scale(data$loc),
           files_std=scale(data$files),
             age_std=scale(get_age(data$created_at))
  )
}

# Prepare data with all categories as factors (1-11).
data <- create_bugs_data(df)
data$category <- factor(df$category)

# Prepare data that factors on the presence of compiler warnings
data_factor_uses_warnings <- create_bugs_data(df)
data_factor_uses_warnings$category <- factor(uses_warnings(df$category))
```

## Define models

### B1

```{r b-model-1, message=FALSE}
fit_model_b1 <- function(name, data) {
  fit_model(name,
            "bugs_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

b1 <- fit_model_b1("b1", data)
```

### B2

```{r b-model-2, message=FALSE}
fit_model_b2 <- function(name, data) {
  fit_model(name,
            "bugs_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

b2 <- fit_model_b2("b2", data)
```

### B3

```{r b-model-3, message=FALSE}
fit_model_b3 <- function(name, data) {
  fit_model(name,
            "bugs_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

b3 <- fit_model_b3("b3", data)
```

### B4

```{r b-model-4, message=FALSE}
fit_model_b4 <- function(name, data) {
  fit_model(name,
            "bugs_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

b4 <- fit_model_b4("b4", data)
```

### B5

```{r b-model-5, message=FALSE}
fit_model_b5 <- function(name, data) {
  fit_model(name,
            "bugs_kloc_std ~ 0 + category + contributors_std + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

b5 <- fit_model_b5("b5", data)
```

### B6

```{r b-model-6, message=FALSE}
fit_model_b6 <- function(name, data) {
  fit_model(name,
            "bugs_kloc_std ~ 0 + category + contributors_std + stars_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

b6 <- fit_model_b6("b6", data)
```

## Compare models

```{r b-compare-models}
b1 <- add_criterion(b1, criterion="loo", moment_match=TRUE)
b2 <- add_criterion(b2, criterion="loo", moment_match=TRUE)
b3 <- add_criterion(b3, criterion="loo", moment_match=TRUE)
b4 <- add_criterion(b4, criterion="loo", moment_match=TRUE)
b5 <- add_criterion(b5, criterion="loo", moment_match=TRUE)
b6 <- add_criterion(b6, criterion="loo", moment_match=TRUE)

print(loo_compare(b1, b2, b3, b4, b5, b6, criterion="loo"), simplify=FALSE)
```


## Prior predictive checks

```{r b-ppc}
plot_priors(b1, "Bugs per KLOC (std)")
```

## Determine natural scale values

```{r b-determine-natural-scale-values}
summary(b1)
print(create_natural_scale_summary_df(b1, df$bugs_kloc))
```

## Intervals of major categories

```{r b-plot-intervals-of-major-categories, fig.width=6, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(b1) +
  labs(title="B1", x="Bugs per KLOC (std)")
```

## Warnings versus no warnings

```{r b-warnings-vs-no-warnings, fig.width=6, fig.height=2, message=FALSE}
b1_factor_uses_warnings <- fit_model_b1("b1_factor_uses_warnings",
                                        data_factor_uses_warnings)

plot_intervals_of_categories(b1_factor_uses_warnings) +
  labs(title="B1", x="Bugs per KLOC (std)") +
  scale_y_discrete(labels=c(
                     "b_category1"="No warnings",
                     "b_category2"="Any warnings"
                   ))
```
