---
author: Albin Johansson & Carl Holmberg
date: 2023
---

```{r mav-include-setup, include=FALSE}
source(knitr::purl("pages/setup.Rmd", output = tempfile()))
```

# Major Violations

This is the section on major violations.

## Prepare Data

```{r mav-prepare-data}
model_seed <- 20230322

create_major_violations_data <- function(data) {
  list(
    major_violations_kloc_std=scale(data$major_violations_kloc),
                    stars_std=scale(data$stars),
             contributors_std=scale(data$contributors),
                      age_std=scale(get_age(data$created_at)),
                     size_std=scale(data$loc),
                    files_std=scale(data$files)
  )
}

data <- create_major_violations_data(df)
data$category <- factor(df$category)

data_factor_uses_warnings <- create_major_violations_data(df)
data_factor_uses_warnings$category <- factor(uses_warnings(df$category))
```

### MAV1

```{r mav-model-1, message=FALSE}
fit_model_mav1 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category",
            c(
              prior(normal(0, 1), class=b),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav1 <- fit_model_mav1("mav1", data)
```

### MAV2

```{r mav-model-2, message=FALSE}
fit_model_mav2 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + contributors_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav2 <- fit_model_mav2("mav2", data)
```

### MAV3

```{r mav-model-3, message=FALSE}
fit_model_mav3 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav3 <- fit_model_mav3("mav3", data)
```

### MAV4

```{r mav-model-4, message=FALSE}
fit_model_mav4 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + files_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="files_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav4 <- fit_model_mav4("mav4", data)
```

### MAV5

```{r mav-model-5, message=FALSE}
fit_model_mav5 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav5 <- fit_model_mav5("mav5", data)
```

### MAV6

```{r mav-model-6, message=FALSE}
fit_model_mav6 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + contributors_std + stars_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav6 <- fit_model_mav6("mav6", data)
```

### MAV7

```{r mav-model-7, message=FALSE}
fit_model_mav7 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + contributors_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="contributors_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav7 <- fit_model_mav7("mav7", data)
```

### MAV8

```{r mav-model-8, message=FALSE}
fit_model_mav8 <- function(name, data) {
  fit_model(name,
            "major_violations_kloc_std ~ 0 + category + stars_std + age_std",
            c(
              prior(normal(0, 1), class=b),
              prior(normal(0, 1), class=b, coef="stars_std"),
              prior(normal(0, 1), class=b, coef="age_std"),
              prior(exponential(1), class=sigma)
            ),
            data,
            model_seed)
}

mav8 <- fit_model_mav8("mav8", data)
```

## Compare models

```{r mav-compare-models, message=FALSE, warning=FALSE}
mav1 <- add_criterion(mav1, criterion="loo", moment_match=FALSE)
mav2 <- add_criterion(mav1, criterion="loo", moment_match=FALSE)
mav3 <- add_criterion(mav3, criterion="loo", moment_match=FALSE)
mav4 <- add_criterion(mav4, criterion="loo", moment_match=FALSE)
mav5 <- add_criterion(mav5, criterion="loo", moment_match=FALSE)
mav6 <- add_criterion(mav6, criterion="loo", moment_match=FALSE)
mav7 <- add_criterion(mav7, criterion="loo", moment_match=FALSE)
mav8 <- add_criterion(mav8, criterion="loo", moment_match=FALSE)

print(loo_compare(mav1, mav2, mav3, mav4, mav5, mav6, mav7, mav8, criterion="loo"),
      simplify=FALSE)
```

## Determine natural scale values

```{r mav-determine-natural-scale-values, message=FALSE}
summary(mav5)
print(create_natural_scale_summary_df(mav5, df$major_violations_kloc))
```

## Intervals of major categories

```{r mav-plot-intervals-of-major-categories, fig.width=6, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(mav5) +
  labs(title="MAV5", x="Major violations per KLOC (std)")
```

## Warnings versus no warnings

```{r mav-warnings-vs-no-warnings, fig.width=6, fig.height=2, message=FALSE}
mav5_factor_uses_warnings <- fit_model_mav5("mav5_factor_uses_warnings",
                                            data_factor_uses_warnings)

plot_intervals_of_categories(mav5_factor_uses_warnings) +
  labs(title="MAV5", x="Major violations per KLOC (std)") +
  scale_y_discrete(labels = c(
    "b_category1"="No warnings",
    "b_category2"="Any warnings"
  ))
```

## Without `clipp`

```{r mav-remove-outliers, message=FALSE}
culled_df <- df
culled_df <- culled_df[culled_df$name != "clipp", ]

culled_data <- create_major_violations_data(culled_df)
culled_data$category <- factor(culled_df$category)

mav5_culled <- fit_model_mav5("mav5_culled", culled_data)
```

```{r mav-determine-natural-scale-values-culled, message=FALSE}
summary(mav5_culled)
print(create_natural_scale_summary_df(mav5_culled, culled_df$major_violations_kloc))
```

```{r mav-plot-intervals-no-outliers, fig.width=6, fig.height=2.8, message=FALSE}
plot_intervals_of_major_categories(mav5_culled) +
  labs(title="MAV5 (culled)", x="Major violations per KLOC (std)")
```

```{r mav-plot-intervals-factor-uses-warnings-no-outliers, fig.width=6, fig.height=2, message=FALSE}
culled_data_factor_uses_warnings <- create_major_violations_data(culled_df)
culled_data_factor_uses_warnings$category <- factor(uses_warnings(culled_df$category))

mav5_culled_data_factor_uses_warnings <- fit_model_mav5(
  "mav5_culled_data_factor_uses_warnings",
  culled_data_factor_uses_warnings
)

plot_intervals_of_categories(mav5_culled_data_factor_uses_warnings) +
  labs(title="MAV5 (culled)", x="Major violations per KLOC (std)") +
  scale_y_discrete(labels=c(
    "b_category1"="No warnings",
    "b_category2"="Any warnings"
  ))
```
